url: "https://wonderful-wescoff-35bc1d.netlify.app" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "My Awesome Jekyll Blog" # the name of your site, e.g. ACME Corp.
excerpt_separator: <!--more-->
plugins:
  - jekyll-archives
jekyll-archives:
  enabled:
    - year
    # - month
    - tags
  layouts:
    tags: tags
    year: year-archive
  permalinks:
    year: '/:year/'
    # month: '/:year/:month/'
    # day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    # category: '/category/:name/'
